### ISSUE TITLE
BUG: Error after final translation files

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#10]
Getting a: `Failed to translate input: {}`
Example: https://github.com/timheuer/tacticview/runs/1401635838?check_suite_focus=true#step:3:259

**Comment by IEvangelist** [comment]
Fixed in release [v2.0.3](https://github.com/IEvangelist/resource-translator/releases/tag/v2.0.3)

**Comment by IEvangelist** [comment]
@all-contributors please add @timheuer for bug and ideas and review
