### ISSUE TITLE
Error: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by yevgen-nykytenko** [IEvangelist/resource-translator#15]
Translation completes successfully, but the job fails with some unclear message
Error: Cannot read property 'data' of undefined
Here is an example - https://github.com/yevgen-nykytenko/resx-translation/runs/1824797965
![image](https://user-images.githubusercontent.com/15048651/106791240-b89da000-6665-11eb-9696-a4f5dc37ed8b.png)

**Comment by IEvangelist** [comment]
I'm so sorry @yevgen-nykytenko - I just now saw this, I apologize. I will take a look at this tonight and try to help fix/debug the issue. Thank you for your patience.

**Comment by IEvangelist** [comment]
This should now be fixed, there was an issue with incorrectly using the raw string rather than the parsed file. Please try again with version [2.1.2](https://github.com/IEvangelist/resource-translator/releases/tag/v2.1.2)

**Comment by yevgen-nykytenko** [comment]
@IEvangelist Just updated to version 2.1.2 and observed the same error again. 
Would you take a look please https://github.com/yevgen-nykytenko/resx-translation/runs/1951218023 ? 
Thanks.

**Comment by IEvangelist** [comment]
Hi again @yevgen-nykytenko - sorry about that, I realized that I never actually built v2.1.2 - i.e.; the `dist/index.js` wasn't updated. I've fixed and correctly pushed this to https://github.com/IEvangelist/resource-translator/releases/tag/v2.1.3

Here is my fork of your repo with it working, thanks again for bringing this to my attention:
https://github.com/IEvangelist/resx-translation/pull/2

**Comment by IEvangelist** [comment]
@all-contributors please add @yevgen-nykytenko for bug

**Comment by RichMercer** [comment]
Was this resolved? I am seeing the same error after setting this up for the first time. 
![image](https://user-images.githubusercontent.com/1423493/121744337-a4c5e700-cafa-11eb-9ed9-aff054f163a9.png)

**Comment by IEvangelist** [comment]
@RichMercer
You need to update versions, this was fixed a while ago - but the version that you're using is 2.1.1 - according to the screen capture. The latest version is 2.1.4, please try that one.

**Comment by RichMercer** [comment]
> @RichMercer
> You need to update versions, this was fixed a while ago - but the version that you're using is 2.1.1 - according to the screen capture. The latest version is 2.1.4, please try that one.

Apologies, I didn't even think to check that. I think I just copied/pasted the code from the readme and didn't bother to check the version. 🤦🏻‍♂️
