### ISSUE TITLE
Error - The maximum request size has been exceeded.

### ISSUE THREAD

**Issue by peters** [IEvangelist/resource-translator#18]
We are in the process of using Azure Cognitive Services for translating a rather large enterprise application. When attempting to translate our resource files to multiple languages the following error is raised. The configured tier in Azure is **S0**. The error message appears to be triggered on longer sentences in our **resx** files. It's impossible with the current error message to identify which resource file and key that is causing the problem. 

![image](https://user-images.githubusercontent.com/869/115512208-00ee5680-a282-11eb-850d-b0b373bdacdf.png)

**Comment by IEvangelist** [comment]
@peters - I'm not sure how I missed this, thank you for reporting this!

**Comment by IEvangelist** [comment]
@all-contributors please add @peters for bug
