### ISSUE TITLE
Stop pull request if not needed

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#3]
Just to avoid unnecessary work, set an output from the translator action maybe (has_new_translations) and look for that as a conditional before the pull request and if not needed, then don't even bother checking.

**Comment by IEvangelist** [comment]
This should be pretty straight-forward, thank you for the suggestion. I'll work on adding that.

**Comment by IEvangelist** [comment]
Fixed in https://github.com/IEvangelist/resource-translator/commit/cc1f6fdffdef12ccc26a095a1c09d1d238a9283e
