### ISSUE TITLE
JSON structure altered

### ISSUE THREAD

**Issue by erjosito** [IEvangelist/resource-translator#33]
Hey there, great job with the repo! I am using this action in https://github.com/Azure/review-checklists/tree/main/checklists, and as you can see in the files, the structure of the original file (for example aks_checklist.en.json) is altered when translated, and arrays are turned into dictionaries (see for example aks_checklist.es.json).

Is this expected?

**Comment by IEvangelist** [comment]
Hi @erjosito - thank you for your kind words. I wrote this for _.resx_ (XML-based) files initially. It was then adapted a bit later for additional scenarios, and while I have tests that validate JSON should work - I have not actually used that specific use case in production. I'd be happy to collaborate on improving the JSON workflow, but I'm a bit strapped for time now so it's not something I can prioritize right now.

Would you be interested in sending over a PR?

**Comment by erjosito** [comment]
I have to admit that TypeScript is not my forte, so I am not sure on how much time it would be involved here...
