### ISSUE TITLE
Do not translate specific JSON keys

### ISSUE THREAD

**Issue by erjosito** [IEvangelist/resource-translator#35]
Hey there,

It would be awesome if you could include the option to specify an array of JSON keys whose values wouldn't be translated.

Azure Translator supports marking certain parts of the origin doc not to be translated, unfortunately that only works for HTML, and not for JSON.

Thanks!

**Comment by IEvangelist** [comment]
This too seems like a good feature ask, I like it. Is this something that you might be interested in adding a PR for?
