### ISSUE TITLE
Errors should fail the action

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#5]
Shouldn't an error fail the action? https://github.com/timheuer/simple-loc-winforms/runs/1388724686?check_suite_focus=true#step:3:8

**Comment by IEvangelist** [comment]
Good catch, you're absolutely right. I'll replace the `error` calls with `setFailed` instead.

**Comment by IEvangelist** [comment]
Fixed in https://github.com/IEvangelist/resource-translator/commit/6493e797b3c262e436c9a863e121a1ccf2f80705
