### ISSUE TITLE
set-output command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by fatihyildizhan** [IEvangelist/resource-translator#55]
Hi, GitHub Actions shows this warning.

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Comment by IEvangelist** [comment]
This should be fixed in release: [v2.2.0](https://github.com/IEvangelist/resource-translator/tree/v2.2.0), where I upgraded all the bits. See ca2e2c1bbbfc1133b4bd364dbe4bdb71d5708b2c
