### ISSUE TITLE
Hits max size quickly

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#6]
This action batches everything together -- this hits the max size quickly.

Example: https://github.com/timheuer/tacticview/runs/1392391527?check_suite_focus=true#step:3:173

**Comment by IEvangelist** [comment]
Great catch, I'll need to appropriately buffer the translate API calls.

**Comment by IEvangelist** [comment]
Fixed in release [v2.0.3](https://github.com/IEvangelist/resource-translator/releases/tag/v2.0.3)

**Comment by IEvangelist** [comment]
Super sad face... this is still broken. https://github.com/IEvangelist/IEvangelist.BlazingTranslations/runs/1403001376?check_suite_focus=true#step:3:413

**Comment by IEvangelist** [comment]
This has since been fixed...
