### ISSUE TITLE
Consider supporting more source file formats

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#7]
Awesome that supports RESX by default...consider making this beyond .NET and supporting XLIFF or others.

**Comment by IEvangelist** [comment]
I love this idea, I can already visualize adding an optional input that defaults to `'resx'`, where the valid choices are one of the union type options. 
```typescript
type ResourceType = 'resx' | 'xliff' | 'restext';
```
Then each will have its own implementation, just have to abstract out some of the inner workings a bit. https://en.wikipedia.org/wiki/XLIFF

Both, `resx` and `xliff` are XML-based whereas the `restext` is newline delimited, key value pairs with `=` assignment semantics. consider adding support for this as well.

### Additional localization sample source code

- https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Localizing%20Analyzers.md
- https://github.com/dotnet/samples/blob/master/csharp/roslyn-sdk/Tutorials/MakeConst/MakeConst/MakeConstAnalyzer.cs 
- https://github.com/microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization

**Comment by IEvangelist** [comment]
Now supports:

- _.ini_
- _.po_
- _.restext_
- _.resx_
- _.xliff_
