### ISSUE TITLE
Consider changing baseResourceGlob

### ISSUE THREAD

**Issue by timheuer** [IEvangelist/resource-translator#8]
Due to an issue how resources are actually looked up in .NET -- if you want to use your base type code-generated static class (old school .NET way -- but you still can) then you're base resource is <file>.resx (no locale) as it is the fallback.

The code: https://github.com/IEvangelist/resource-translator/blob/da5ffa9dd8d7328146995a9c5b8f8cb91fb1f377/src/resource-translator.ts#L40 assumes to map `sourceLocale` to the file name and make that the lookup.  I had thought sourceLocale just feeds into the API call but not hard-coding the path lookup.

Recommend changing this to be perhaps something different.

**Comment by IEvangelist** [comment]
That's a fair callout. I was thinking, perhaps this could be changed to just use the `sourceLocale` as part of the file against the `files` array returned from the GitHub call to get the details from the in context changed the caused the action to run. I'll have to think about this more. I was also considering adding an `inputType: 'resx' | 'xliff';`. This too would change the inputs...

**Comment by IEvangelist** [comment]
This is done, now the paths used to trigger the action are also part of the workflow. The action will take into account all of the various types it supports and cross those with the files that triggered the action to run.
